name: Trigger auto deployment for containerappnukano052201

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'app/backend/**'
    - '.github/workflows/containerappnukano052201-AutoDeployTrigger-da0322b7-8154-48c6-8470-6b7c01556cce.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPNUKANO052201_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/app/backend 
          registryUrl: containerregistrynukano052201.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPNUKANO052201_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNUKANO052201_REGISTRY_PASSWORD }}
          containerAppName: containerappnukano052201
          resourceGroup: rg-nukano0522-01
          imageToBuild: containerregistrynukano052201.azurecr.io/containerappnukano052201:${{ github.sha }}
          
            

     

